#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Find and use FVM's dart
if [ -f "$(pwd)/.fvm/flutter_sdk/bin/dart" ]; then
  "$(pwd)/.fvm/flutter_sdk/bin/dart" run commitlint_cli --edit "$1"
elif [ -f "$(pwd)/fvm/default/bin/dart" ]; then
  "$(pwd)/fvm/default/bin/dart" run commitlint_cli --edit "$1"
else
  echo "Could not find dart executable. Please ensure FVM is properly set up."
  exit 1
fi

